### ISSUE TITLE
Test all supported configurations after merge/validate

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#1056]
IPv8 is supposed to run for all combinations of OS `Linux/Windows/Mac` and Python versions `3.7/3.8/3.9/3.10/3.11`. We only test a select subset of these combinations for PRs (namely `Linux+Python3.7`, `Windows+Python 3.8` and `Mac+Python3.8`). Because some combinations are not tested, this could lead to new code introducing hidden incompatibilities.

To assure that IPv8 runs on all the operating systems and Python versions that we claim to support, we should run the unit tests on all of the supported OS+Python combinations for every merged PR (either just before or just after merging).

**Comment by drew2a** [comment]
One of the easiest ways to do it is to use [Travis Build Matrix](https://docs.travis-ci.com/user/build-matrix/)

**Comment by qstokkink** [comment]
We should probably also run the entire test suite on each build environment twice: for IPv4 and IPv6. For reference: the tests use IPv4 (default) if `ipv8.test.mocking.endpoint.ADDRESS_TYPE = "UDPv4Address"` and IPv6 if `ipv8.test.mocking.endpoint.ADDRESS_TYPE = "UDPv6Address"`. At the time of writing, the latter is still expected to break until #615 is resolved.

**Comment by qstokkink** [comment]
We should probably also make sure to test all supported test runners: `unittest` (which is the most important), `nose` and `pytest`. I'm not sure if other runners are supported, perhaps `trial`?

**Comment by drew2a** [comment]
@qstokkink you might also want to consider the option (3). To divide checks into two groups and run the first group when PR is in the "draft" state, and the second when PR is in the "ready to review" state.

See the example of Tribler's PR checks:
```yml
  coverage:
    uses: ./.github/workflows/coverage.yml
    with:
      python-version: 3.8

  pytest:
    uses: ./.github/workflows/pytest.yml
    with:
      python-version: 3.8

  guitest:
    uses: ./.github/workflows/guitest.yml
    with:
      python-version: 3.8

  documentation:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/documentation.yml
    with:
      python-version: 3.8

  ubuntu:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build_ubuntu.yml
    with:
      upload: false
      os: ubuntu-20.04
      python-version: 3.8
```
https://github.com/Tribler/tribler/blob/main/.github/workflows/!PR.yml
